steps:
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'dataflow/ngrams'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION']
  - name: 'gcr.io/cloud-builders/gcloud'
    dir: 'dataflow/ngrams'
    args: [
        'dataflow',
        'flex-template',
        'build',
        'gs://$_TEMPLATE_BUCKET/templates/$_TEMPLATE_VERSION/$_TEMPLATE_NAME.json',
        '--image', 'gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION',
        '--sdk-language', 'PYTHON',
        '--metadata-file', '$_METADATA_FILE'
    ]
images: ['gcr.io/$PROJECT_ID/$_IMAGE_NAME:$_IMAGE_VERSION']
substitutions:
  _IMAGE_NAME: "ngrams-beam"
  _IMAGE_VERSION: "1.0.0"
  _TEMPLATE_NAME: "ngrams-beam"
  _TEMPLATE_VERSION: "1.0.0"
  _TEMPLATE_BUCKET: "gcp-pdp-words-dev-dataflow"
  _METADATA_FILE: "metadata.json"